### ISSUE TITLE
Support for calc

### ISSUE THREAD

**Issue by guivr** [dawaltconley/bg-size-parser#1]
Hi, first of all, thank you SO MUCH for this library! :)

I noticed that it doesn't work with calc() values, example:
`background-size: calc(100% + 200px) 100px`

**Comment by dawaltconley** [comment]
Glad you're finding it useful! And thank you for the issue; yes this definitely should not break it.

At the moment I think I want to just return the full `calc` string (as either width or height) and leave parsing its contents to other libraries. But also need to be sure it's distinguishable from other values like keywords.

Am thinking best solution is to add a "type" property that can be either "calc", "length", "var" (should support this), and "keyword". But this will break the current way of handling keywords so I'll push a quick-and-dirty fix for calc/var first.

**Comment by dawaltconley** [comment]
Just added; now the following should work.

```javascript
parse('calc(100% + 200px) 100px');

// [
//   {
//     width: { calculation: 'calc(100% + 200px)' },
//     height: { size: 100, unit: 'px' }
//   }
// ]
```

**Comment by guivr** [comment]
That's amazing, thank you so much!
